Document: mpir
Title: Debian mpir Manual
Author: <insert document author here>
Abstract: This manual describes what mpir is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mpir/mpir.sgml.gz

Format: postscript
Files: /usr/share/doc/mpir/mpir.ps.gz

Format: text
Files: /usr/share/doc/mpir/mpir.text.gz

Format: HTML
Index: /usr/share/doc/mpir/html/index.html
Files: /usr/share/doc/mpir/html/*.html
